---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-kibana
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: ubuntu-kibana
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
