---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  # - name: Example assertion
  #   assert:
  #     that: true
  - name: Check logstash
    become: true
    shell: /usr/share/logstash/bin/logstash -e 'input { stdin { } } output { stdout {} }'
    register: logstash_is_running
  - name: assert 
    assert:
      that: "'Successfully started Logstash API endpoint' in logstash_is_running.stdout"
      quiet: true  


