---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  # - name: Example assertion
  #   assert:
  #     that: true
  - name: Check logstash
    become: true
    command: /usr/share/logstash/bin/logstash -e 'input { stdin { } } output { stdout {} }'
    register: logstash_is_running
  - debug:
      var: logstash_is_running


  # - name: set correct fact
  #   set_facts: 
  #     dbg_msg: "Successfully started Logstash API endpoint"
  # - name: enshure message is sent
  #   assert:
  #     that:
  #       - "'d'"